version: '3'

services:
  devenv:
    container_name: devenv-py-ml
    build:
      context: ./
    image: nemuvski/python-ml-kit:py3.6.4-alpine3.7
    volumes:
      - ./workspace:/home/dev/workspace
    command: sh
